[package]
name = "finance_data_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
rkyv = "0.8.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = "3.14.0"
sqlite = "0.37.0"
